packages/frontend/package.json
pnpm-lock.yaml

fix: add spartan-ecdsa in frontend/

---

packages/frontend/package.json
packages/frontend/src/components/PostMessage.tsx

TODO: added my own hosted Postgres database to get the deploy working so we can update it later.

[DEPLOYMENT]: Update deploy script

---

package.json
packages/frontend/src/pages/api/v1/posts/[postId].ts
pnpm-lock.yaml

Update the endpoint `GET /posts/{postId}` to return nested replies, instead of a flat array.
1. If you haven't already, [populate the state](https://github.com/personaelabs/nym/blob/main/packages/test_data/README.md).
2. Start the frontend dev server and navigate to http://localhost:3000/api-doc
3. Get a post id from the database, and execute `/posts/{postId}` from the Swagger UI.
```
{
"id": "0x97e5f11dc753cf346b041fe8c4865d5379d83ae712c51b11d960e0ad64ae682a",
"title": "Tips for healthy eating",
"body": "Healthy eating is essential for maintaining a balanced lifestyle. What are some tips and tricks you use to make healthy choices and stay on track? Let's share our favorite recipes and strategies for eating well!",
"parentId": "0x0",
"upvotes": 0,
"timestamp": "2023-05-04T08:06:48.000Z", …
```

[READY FOR REVIEW] Return nested replies

---

packages/frontend/src/components/MessageRow.tsx
packages/frontend/src/pages/post/[postId].tsx

Add specific comment route

---

packages/circuits/package.json
packages/frontend/package.json
packages/frontend/src/components/example/PostMessage.tsx
packages/frontend/src/pages/api/v1/posts.ts
packages/frontend/src/pages/api/v1/users/[userId]/posts.ts
packages/frontend/src/pages/api/v1/users/[userId]/upvotes.ts
packages/frontend/src/pages/api/v1/utils.ts
packages/merkle_tree/package.json
packages/nymjs/package.json
packages/test_data/package.json
pnpm-lock.yaml

Fix Nym post submission in the example page.
This fix should allow Nym post creation (including the proving) to be possbile from the example page. The actual UI can reference the code in the example to implement nym post submission!
This is ready to be merged!

Fix example Nym post submission

---

packages/frontend/src/components/NestedReply.tsx
packages/frontend/src/components/Post.tsx
packages/frontend/src/components/PostWithReplies.tsx
packages/frontend/src/components/Posts.tsx
packages/frontend/src/pages/api/v1/users/[userId]/posts.ts
packages/frontend/src/pages/api/v1/users/[userId]/upvotes.ts
packages/frontend/src/pages/posts/[postId].tsx
packages/frontend/types/api/userUpvotesSelect.ts
packages/frontend/types/components/index.ts

Client Clean

---

packages/frontend/src/components/Posts.tsx
packages/frontend/src/components/Upvote.tsx
packages/frontend/src/components/UpvoteIcon.tsx
packages/frontend/src/components/UpvoteWarning.tsx
packages/frontend/src/components/WalletWarning.tsx
packages/frontend/src/components/post/NestedReply.tsx
packages/frontend/src/components/post/PostWithReplies.tsx
packages/frontend/types/components/index.ts

Upvoting UI

---

packages/frontend/src/components/Upvote.tsx
packages/frontend/src/components/post/NestedReply.tsx
packages/frontend/src/components/post/UserTag.tsx
packages/frontend/src/components/userInput/PostWriter.tsx

Upvoting Pt 2

---

packages/frontend/src/components/Posts.tsx
packages/frontend/src/components/Upvote.tsx
packages/frontend/src/components/global/Modal.tsx
packages/frontend/src/components/post/NestedReply.tsx
packages/frontend/src/components/post/Post.tsx
packages/frontend/src/components/post/PostWithReplies.tsx
packages/frontend/src/components/post/UserTag.tsx
packages/frontend/src/components/userInput/NewPost.tsx
packages/frontend/src/components/userInput/PostWriter.tsx
packages/frontend/src/pages/posts/[postId].tsx
packages/frontend/src/pages/users/[userId].tsx
packages/frontend/types/components/index.ts

Post Responsiveness

---

packages/circuits/tests/nym_ownership.test.ts
packages/circuits/tests/test_utils.ts

Add a test to check that all inputs are constrained.
How to test:
```
cd packages/circuits  && pnpm test
```
Nothing too complicated!
Lmk if you have ideas on other tests we should run.

Add circuit input constraint test

---

packages/frontend/src/components/Posts.tsx
packages/frontend/src/components/global/Seo.tsx
packages/frontend/src/components/post/PostWithReplies.tsx
packages/frontend/src/pages/api/v1/posts/[postId].ts
packages/frontend/src/pages/users/[userId].tsx
packages/frontend/types/api/postSelect.ts
packages/frontend/types/components/index.ts

Modify API route to go to a post preview from any post link.
Known bug: If the post is > 5 levels deep, it will not appear in the post with replies.

Fix Post With Replies

---

packages/frontend/src/components/Posts.tsx
packages/frontend/src/components/Upvote.tsx
packages/frontend/src/components/post/NestedReply.tsx
packages/frontend/src/components/post/PostPreview.tsx
packages/frontend/src/components/post/PostWithReplies.tsx
packages/frontend/src/components/post/SingleReply.tsx
packages/frontend/src/components/userInput/PostWriter.tsx
packages/frontend/src/lib/actions.ts

This PR improves UI feedback on post submission. The new UI flow is as follows:
1. On click of the `Send` button, a spinner appears and runs while the user is signing and submitting their post to the server
2. Once response from server is received, the data is refetched and the page scrolls to the new post (if exists)

Post submission user feedback

---

README.md
packages/frontend/src/components/global/RetryError.tsx
packages/frontend/src/components/post/UserTag.tsx
packages/frontend/src/pages/api/v1/users.ts
packages/frontend/src/pages/api/v1/utils.ts
packages/frontend/src/pages/posts/[postId].tsx
packages/frontend/src/pages/users.tsx

Finalize Users Page

---

packages/frontend/src/components/Posts.tsx
packages/frontend/src/components/Upvote.tsx
packages/frontend/src/components/post/CopyLink.tsx
packages/frontend/src/components/post/PostPreview.tsx
packages/frontend/src/components/post/ReplyCount.tsx
packages/frontend/src/components/post/SingleReply.tsx
packages/frontend/src/pages/users/[userId].tsx

This PR implements a URL change whenever a `PostWithReplies` modal is opened and closed. It also adds a `Copy Link` button to each post/reply that copies a link to the post to the clipboard.

Client-side routing

---

packages/frontend/next.config.js
packages/frontend/src/components/global/Seo.tsx
packages/frontend/src/components/global/UserAvatar.tsx
packages/frontend/src/hooks/useUserInfo.ts
packages/frontend/src/pages/posts/[postId].tsx

- HTML Title for Posts
- ENS Avatar
- Next Image rendering

Smol things

---

packages/frontend/src/components/Header.tsx
packages/frontend/src/components/MyProfile.tsx
packages/frontend/src/components/Posts.tsx
packages/frontend/src/components/global/ErrorPage.tsx
packages/frontend/src/components/global/Modal.tsx
packages/frontend/src/components/global/RouteLoadingSpinner.tsx
packages/frontend/src/components/post/NestedReply.tsx
packages/frontend/src/components/post/PostPreview.tsx
packages/frontend/src/components/post/PostWithReplies.tsx
packages/frontend/src/components/post/SortSelect.tsx
packages/frontend/src/components/post/UserTag.tsx
packages/frontend/src/components/userInput/NameMenuItem.tsx
packages/frontend/src/components/userInput/NameSelect.tsx
packages/frontend/src/components/userInput/NewNym.tsx
packages/frontend/src/components/userInput/PostWriter.tsx
packages/frontend/src/hooks/useError.ts
packages/frontend/src/hooks/usePushRoute.ts
packages/frontend/src/lib/client-utils.ts
packages/frontend/src/pages/404.tsx
packages/frontend/src/pages/500.tsx
packages/frontend/src/pages/_app.tsx
packages/frontend/src/pages/index.tsx
packages/frontend/src/pages/posts/[postId].tsx
packages/frontend/src/pages/users.tsx
packages/frontend/src/pages/users/[userId].tsx
packages/frontend/src/styles/globals.css
packages/frontend/types/components/index.ts

UI Improvements

---

packages/frontend/src/components/DiscardPostWarning.tsx
packages/frontend/src/components/MainButton.tsx
packages/frontend/src/components/Posts.tsx
packages/frontend/src/components/UpvoteWarning.tsx
packages/frontend/src/components/global/ErrorPage.tsx
packages/frontend/src/components/post/NestedReply.tsx
packages/frontend/src/components/post/PostWithReplies.tsx
packages/frontend/src/components/post/PostWithRepliesModal.tsx
packages/frontend/src/components/post/UserTag.tsx
packages/frontend/src/components/userInput/NewPost.tsx
packages/frontend/src/components/userInput/PostWriter.tsx
packages/frontend/src/pages/_app.tsx
packages/frontend/src/pages/posts/[postId].tsx
packages/frontend/src/pages/users.tsx
packages/frontend/src/pages/users/[userId].tsx
packages/frontend/types/components/index.ts

Client Fixes

---

scripts/warmup_cron.sh

Will call the script every minute from Render

Add script to warmup Vercel instances

---

packages/frontend/src/lib/errors.ts
packages/frontend/src/pages/api/v1/posts.ts
packages/frontend/test/api.test.ts

Just simple checks and simple tests!

Verify that title/body are filled in the backend

---

packages/frontend/src/components/Header.tsx
packages/frontend/src/components/MyProfile.tsx
packages/frontend/src/components/Posts.tsx
packages/frontend/src/components/Upvote.tsx
packages/frontend/src/components/UpvoteWarning.tsx
packages/frontend/src/components/post/NestedReply.tsx
packages/frontend/src/components/post/PostWithReplies.tsx
packages/frontend/src/components/post/PostWithRepliesModal.tsx
packages/frontend/src/components/post/ReplyCount.tsx
packages/frontend/src/components/userInput/NewPost.tsx
packages/frontend/src/components/userInput/PostWriter.tsx
packages/frontend/src/pages/_app.tsx
packages/frontend/src/pages/posts/[postId].tsx
packages/frontend/types/components/index.ts

Forgot to make a PR for this and these changes nearly got lost in the sauceeeee

Fixes Pt. 1

---

packages/frontend/src/components/Header.tsx
packages/frontend/src/components/MyProfile.tsx
packages/frontend/src/components/Posts.tsx
packages/frontend/src/components/Upvote.tsx
packages/frontend/src/components/UpvoteWarning.tsx
packages/frontend/src/components/notifications/Notifications.tsx
packages/frontend/src/components/notifications/NotificationsTools.tsx
packages/frontend/src/components/post/NestedReply.tsx
packages/frontend/src/components/post/PostWithReplies.tsx
packages/frontend/src/components/post/PostWithRepliesModal.tsx
packages/frontend/src/components/post/ReplyCount.tsx
packages/frontend/src/components/post/SingleReply.tsx
packages/frontend/src/components/userInput/NameSelect.tsx
packages/frontend/src/components/userInput/NewNym.tsx
packages/frontend/src/components/userInput/NewPost.tsx
packages/frontend/src/components/userInput/PostWriter.tsx
packages/frontend/src/hooks/useNotifications.ts
packages/frontend/src/lib/client-utils.ts
packages/frontend/src/pages/_app.tsx
packages/frontend/src/pages/faq.tsx
packages/frontend/src/pages/index.tsx
packages/frontend/src/pages/notifications.tsx
packages/frontend/src/pages/posts/[postId].tsx
packages/frontend/src/pages/users/[userId].tsx
packages/frontend/types/components/index.ts
packages/frontend/types/notifications/index.ts

https://github.com/personaelabs/nym/assets/95446735/3222c05e-f4cd-418c-9dbd-093efefa92a0

Client Bug Fixes

---

packages/frontend/src/components/Upvote.tsx

Fixes a bug that causes the document to focus on the first upvote button on initial page load

Fix: Initial Focus

---

CONTRIBUTING.md
README.md
packages/nymjs/README.md

top-level README, nymjs README, basic contribution guidelines
TODO:

various launch docs

---

packages/frontend/package.json
packages/frontend/src/components/MyProfile.tsx
packages/frontend/src/components/Posts.tsx
packages/frontend/src/components/Upvote.tsx
packages/frontend/src/components/global/RouteLoadingSpinner.tsx
packages/frontend/src/components/post/CopyLink.tsx
packages/frontend/src/components/post/PostPreview.tsx
packages/frontend/src/components/post/PostWithReplies.tsx
packages/frontend/src/components/post/ReplyCount.tsx
packages/frontend/src/components/post/SingleReply.tsx
packages/frontend/src/components/post/UserTag.tsx
packages/frontend/src/components/userInput/NameSelect.tsx
packages/frontend/src/components/userInput/NewNymMenuItem.tsx
packages/frontend/src/components/userInput/NewNymModal.tsx
packages/frontend/src/components/userInput/PostWriter.tsx
packages/frontend/src/lib/text.ts
packages/frontend/src/pages/index.tsx
packages/frontend/src/pages/notifications.tsx
packages/frontend/src/pages/posts/[postId].tsx
packages/frontend/src/styles/globals.css
pnpm-lock.yaml

- Fixes #203 
- Fixes #211 
- Fixes #206 and a few other mobile spacing issues:
**Before / After:**
<div style="display:flex;">
</div>

Mobile spacing & 🛠️

---

packages/frontend/src/components/post/NestedReply.tsx
packages/frontend/src/components/post/PostWithReplies.tsx
packages/frontend/src/components/post/ShowMore.tsx
packages/frontend/src/components/post/SingleReply.tsx
packages/frontend/src/components/userInput/NewNymModal.tsx
packages/frontend/src/lib/text.ts
packages/frontend/types/api/postSelect.ts

Closes #213
Closes #209 
https://share.cleanshot.com/JZ7xRrFD for demo
TODO:

Fetch siblings

---

packages/frontend/.gitignore
packages/frontend/package.json
packages/frontend/src/components/post/PostPreview.tsx
packages/frontend/src/components/post/PostWithReplies.tsx
packages/frontend/src/components/post/SingleReply.tsx

Closes #210 
It's just an HTML rendering thing!
I replaced `<p>` and `<span>` tags with `<pre>` and newlines work. Only problem is that styling is now broken cc @grace-fagan

Allow new lines

---

packages/frontend/src/components/User.tsx
packages/frontend/src/components/global/UserAvatar.tsx
packages/frontend/src/components/post/UserTag.tsx
packages/frontend/src/hooks/useName.ts
packages/frontend/src/pages/api/v1/utils.ts

Show (pseudo) in link preview and in client

---

packages/frontend/src/pages/_app.tsx

Wallet connect id 

---

packages/frontend/src/components/proposals/BodyWithPropLink.tsx
packages/frontend/src/hooks/useNotifications.ts

Notifications Fix
