personaelabs/noun-nyms

packages/circuits/package.json, packages/frontend/package.json, packages/merkle_tree/package.json, packages/nymjs/package.json, packages/test_data/package.json, pnpm-lock.yaml
[spartan-ecdsa v.2.1.2](https://github.com/personaelabs/spartan-ecdsa/releases/tag/v2.1.2) makes Poseidon hashing considerably faster (by lazy loading the Poseidon constants to global memory instead of loading them every time the hash function is called).
Confirmed that all tests pass.
Feel free to merge on approval!
=> [READY FOR REVIEW] Bump spartan-ecdsa to v2.1.2

render.yaml
Setup [Infrastructure as Code](https://render.com/docs/infrastructure-as-code) for the merkle-tree service and the database in Render.
The main motivation is to use [Preview Environments](https://render.com/docs/preview-environments), which deploys a new set of services (including the database) defined in render.yaml for every PR. With this, we can have a “staging” environment for the merkle tree service.
The existing services of prop150 [won’t be deleted](https://render.com/docs/infrastructure-as-code#no-automatic-deletions). And we probably don’t want to add their information to render.yaml since that could unexpectedly update the configuration of the services.
Once this PR is merged, we can apply render.yaml from the `Blueprints` tab in the Render dashboard.
I tested the render.yaml …
=> [WIP] Add IaC for Render (Staging env setup)

packages/frontend/package.json, packages/test_data/package.json
Update pnpm commands to only set `DATABASE_URL` to the local url in development environments.
In test_data/, we set `.env` to `.example.env` only if `DATABASE_URL` is not defined already. (In Render, `DATABASE_URL` is defined during build).
For frontend/, we copy `.env.example` to `.env` only when `pnpm run dev` is called. The reason for the difference in approaches between frontend/ and test_data/ is: for Vercel previews, we need to manually copy-paste the `DATABASE_URL` so `DATABASE_URL` is not set during preview builds. (i.e. cannot rely on the availability of `DATABASE_URL` for preview builds)
=> [READY FOR REVIEW] Only copy .env.example to .env in development environments

packages/frontend/.eslintrc.json, packages/frontend/next.config.js, packages/frontend/package.json, pnpm-lock.yaml
This PR cleans up two warnings:
Fixed by recommendation [here](https://github.com/vercel/next.js/issues/40687#issuecomment-1421526821)
```
warn  - ../../node_modules/.pnpm/web-worker@1.2.0/node_modules/web-worker/cjs/node.js
Critical dependency: the request of a dependency is an expression
Import trace for requested module:
../../node_modules/.pnpm/web-worker@1.2.0/node_modules/web-worker/cjs/node.js
../../node_modules/.pnpm/ffjavascript@0.2.56/node_modules/ffjavascript/build/main.cjs
../../node_modules/.pnpm/snarkjs@0.5.0/node_modules/snarkjs/build/main.cjs
../nymjs/build/utils.js
../nymjs/build/lib.js
```
Fixed by recommendation [here](https://typeorm.io/faq#how-to-use-webpack-for-the-backend)
=> Clean up warnings

packages/frontend/src/components/MainButton.tsx, packages/frontend/src/components/UpvoteIcon.tsx, packages/frontend/src/components/example/PostMessage.tsx, packages/frontend/src/components/global/Modal.tsx, packages/frontend/src/components/post/NestedReply.tsx, packages/frontend/src/components/post/PostWithReplies.tsx, packages/frontend/src/components/userInput/CommentWriter.tsx, packages/frontend/src/components/userInput/NewNym.tsx, packages/frontend/src/components/userInput/NewPost.tsx, packages/frontend/src/components/userInput/NymSelect.tsx, packages/frontend/src/styles/globals.css, packages/frontend/types/components/index.ts
On `openSelect`, check local storage and get list of pre-created nyms
1. Get doxed id
2. Existing nyms (if any)
3. Option to create new nym
**Case 1:** User posts with doxed id
- Pass doxed id to `postDoxed`
**Case 2:** User selects nym from pre-existing options
- Pass nymSig and nymName from local storage to `postPseudo`
**Case 3:** User creates new nym
- `signNym` with nymName, get nymSig
- Pass nymSig and nymName to `postPseudo`
**Questions**
_Should the be an option to remove an existing nym?_
=> Nym Selection / Pseudo Posting

packages/frontend/src/components/example/PostMessage.tsx, packages/frontend/src/components/userInput/NewNym.tsx, packages/nymjs/src/core/prover.ts, packages/nymjs/src/types.ts, packages/nymjs/src/utils.ts
Add a warning to the message which yields the nym sig.
- The domain `nymz.xyz` is temporary; we can change it after getting the actual domain.
- Not the prettiest UX, but I'm not sure if we can do any better. Lmk if you have any suggestions! (especially the wording of the warning message; we should warn users properly but don't wanna scare them).
=> Add a warning in the nym sig message

packages/frontend/src/components/Header.tsx, packages/frontend/src/components/Posts.tsx, packages/frontend/src/components/Upvote.tsx, packages/frontend/src/components/UpvoteWarning.tsx, packages/frontend/src/components/WalletWarning.tsx, packages/frontend/src/components/global/Modal.tsx, packages/frontend/src/components/post/Post.tsx, packages/frontend/src/components/post/PostWithReplies.tsx, packages/frontend/src/components/userInput/NewNym.tsx, packages/frontend/src/components/userInput/NewPost.tsx, packages/frontend/src/components/userInput/NymSelect.tsx, packages/frontend/src/components/userInput/PostWriter.tsx, packages/frontend/src/pages/users/[userId].tsx, packages/frontend/types/components/index.ts
=> Modal Fixes

packages/frontend/src/components/global/UserAvatar.tsx, packages/frontend/src/components/post/UserTag.tsx, packages/frontend/src/components/userInput/NewNym.tsx, packages/frontend/src/components/userInput/NymSelect.tsx, packages/frontend/src/components/userInput/PostWriter.tsx, packages/frontend/types/components/index.ts
Closes #105 
> - [x] Show avatar for doxed user in selection panel
> - [x] Show avatar for nym in selection panel 
To Do:
=> Nym Selection Improvements

packages/frontend/src/lib/avatar-utils.ts
This fixes a bug which caused collisions to occur with nyms because we were not correctly checking if the `userId` (which is just a hex value) or a nym machine readable code (where we need to remove the nym prefix to get to the hex string).
=> Fix avatar collisions by handling addresses and nyms separately

packages/db/prisma/migrations/20230520191158_add_column_address/migration.sql, packages/db/prisma/schema.prisma, packages/frontend/src/pages/api/v1/groups/latest.ts, packages/merkle_tree/src/writeTree.ts, packages/test_data/scripts/populateTestData.ts
Add an `address` column to `TreeNode`.
- First, delete all rows in the `TreeNode` table. (This is necessary because we’re adding a non-null column)
- Run `pnpm -F db migrate:dev` to add the column
- Run `pnpm test_data:populate` to update re-populate the test data
@cha0sg0d  To check if an address is in a group, you can use the [GET groups/latest endpoint](https://github.com/personaelabs/nym/blob/2cb51c4f85e5d2c9b21b45b31e2734ba16db56d1/packages/frontend/src/pages/api/v1/groups/latest.ts#L6) to get all members in a group, and check the inclusion it in the frontend!
(We don't wanna have an endpoint that takes an address and returns true/false re the inclusion, because that'll break pseudonymity.)
=> Add column `address` to `TreeNode`

packages/test_data/scripts/populateTestData.ts
I ran the test data population script from my local env targeting the staging db, so we should now be able to submit posts/upvotes with our ENS in staging.
(Nothing will happen upon merging this PR)
=> Add ENS addresses to test data group

packages/frontend/src/components/post/UserTag.tsx
Fixes a small UI bug where the user tag is outline when a post is clicked
Before:
After:
=> [READY FOR REVIEW] Remove outline on user tag when post is clicked

packages/db/prisma/migrations/20230525132316_add_column_depth/migration.sql, packages/db/prisma/schema.prisma, packages/frontend/src/lib/errors.ts, packages/frontend/src/pages/api/v1/posts.ts, packages/frontend/src/pages/api/v1/utils.ts, packages/frontend/test/api.test.ts, packages/test_data/scripts/populateTestData.ts
Add column `depth` to `Post`.
On staging, I deleted all `Post` records (and `Upvote` due to foreign key relation) and ran the migration, adding the `depth` column. Also re-populated the staging db with test data.
=> Add depth count to `Post`

packages/frontend/src/components/userInput/NameSelect.tsx
Refresh `nymOptions` when the address changes so the content is signed with the same account as the selected nym.
After implementing this fix, I haven't encountered the proof generation issue, but there could be other causes, so let's keep an eye on proof generation failures.
Closes #130 ( we think )
=> Fix proving bug

packages/frontend/.gitignore, packages/frontend/next.config.js, packages/frontend/package.json, packages/frontend/sentry.client.config.ts, packages/frontend/sentry.server.config.ts, pnpm-lock.yaml
Add the Sentry sdk to frontend/. Both server-side and client-side errors will be reported to our Sentry workspace.
I tried configuring the SDK NOT to send the client information (browser, device info) as much as possible. But there could still be some things sent that could lead to reducing anonymity. (For example, in an extreme case, a nymNam and an ETH address are sent in a single error message).
I considered not using any error reporting SDK as well due to its possible privacy-breaking features, but I think we can experiment with it during development and see what it could leak.
Replace `packages/frontend/src/pages/index.tsx` with the following to test reporting an error from the frontend. I invited everyone on the team to the Sentry workspace, so you should be able to see the error …
=> Sentry setup

packages/circuits/package.json, packages/circuits/tests/nym_ownership.test.ts, packages/frontend/package.json, packages/frontend/src/components/example/PostMessage.tsx, packages/frontend/src/components/userInput/PostWriter.tsx, packages/frontend/src/hooks/useProver.ts, packages/frontend/src/lib/actions.ts, packages/frontend/test/api.test.ts, packages/merkle_tree/package.json, packages/nymjs/package.json, packages/nymjs/src/core/prover.ts, packages/nymjs/src/errors.ts, packages/nymjs/src/utils.ts, packages/nymjs/tests/nym.test.ts, packages/test_data/package.json, pnpm-lock.yaml
Improvements
- Throw an error when **1. the signer of the nymSig and contentSig are different 2. the Merkle proof is invalid.** This is better than the errors the circuit throws (which only indicates which constraint failed) for debugging.
- Expose a `loadCircuit` from `NymProver` so the frontend can fetch the circuit as soon as the page renders, which improves perceived proving time. I implement this improvement with the custom hook [useProver](https://github.com/personaelabs/nym/blob/dan/improve-proving/packages/frontend/src/hooks/useProver.ts).
Notable changes
- I updated spartan-ecdsa to expose the `verifyProof` from the `Tree` class. We use the method to verify the Merkle proof in`NymProver`.
=> Improve proving

packages/frontend/src/components/ConnectWallet.tsx, packages/frontend/src/components/Header.tsx, packages/frontend/src/components/MyProfile.tsx, packages/frontend/src/components/Posts.tsx, packages/frontend/src/components/global/Modal.tsx, packages/frontend/src/components/post/CopyLink.tsx, packages/frontend/src/components/post/Filters.tsx, packages/frontend/src/components/post/PostPreview.tsx, packages/frontend/src/components/post/PostWithReplies.tsx, packages/frontend/src/components/post/SingleReply.tsx, packages/frontend/src/components/post/SortSelect.tsx, packages/frontend/src/components/post/UserTag.tsx, packages/frontend/src/components/userInput/NameSelect.tsx, packages/frontend/src/components/userInput/PostWriter.tsx, packages/frontend/src/hooks/useUserInfo.ts, packages/frontend/src/pages/_app.tsx, packages/frontend/src/pages/posts/[postId].tsx, packages/frontend/src/pages/users.tsx, packages/frontend/src/pages/users/[userId].tsx, packages/frontend/src/styles/globals.css, packages/frontend/types/components/index.ts
> - [ ] Add slideUp transitions
- Used tailwind media queries when possible
- Conditional template rendering uses a `UserContext` attribute `isMobile`
- Fix `lastActive` filter on users page
- Added `Top` and `Recent` filters to the posts page
- Added `Posts` and `Replies` filters to the [userId] page (WIP)
=> Mobile Responsiveness

packages/frontend/public/api-doc.yml, packages/frontend/src/components/post/PostWithReplies.tsx, packages/frontend/src/pages/api/v1/posts/[postId]/fetchParents.ts
This PR adds support for deep-linking posts in all threads including
- comment threads which are available client-side (i.e. <5 depth on initial load)
- comments threads which are deeper than depth 5 and are not returned in the first server load data (so we need to go out and fetch it)
Demo:
https://drive.google.com/file/d/1JsMdEb1V3_3J39VMeuWXjvNZm_YhSI3Q/view?usp=drive_link
=> [READY FOR REVIEW] Support deep-linking with new threading

packages/frontend/src/components/Header.tsx, packages/frontend/src/components/MyProfile.tsx, packages/frontend/src/components/global/Providers.tsx, packages/frontend/src/components/notifications/Notifications.tsx, packages/frontend/src/components/notifications/RefreshNotifications.tsx, packages/frontend/src/components/notifications/SingleNotification.tsx, packages/frontend/src/hooks/useNotifications.ts, packages/frontend/src/hooks/useStupidHook.ts, packages/frontend/src/pages/_app.tsx, packages/frontend/src/pages/api/v1/notifications.ts, packages/frontend/src/pages/notifications.tsx, packages/frontend/types/api/index.ts, packages/frontend/types/api/notifications.ts, packages/frontend/types/api/userUpvotesSelect.ts, packages/frontend/types/components/index.ts, packages/frontend/types/notifications/index.ts
- Fixes hydration error (was caused by Wagmi hook again lol)
- Cleans up logic to mark all as read
Known problems:
- If wallet is not connected, user's profile doesn't exist.
- Means we have no easy way to show the `Users` page to site visitors. 
- Marking a notification as read doesn't propagate between `notifications` and `Notifications.tsx`. Also, because I learned that hooks are like copies of state, not shared state, `refetchNotifications` won't actually re-render our new values so that needs to be in a Context as well.
=> Notifications again

packages/frontend/src/components/Header.tsx, packages/frontend/src/components/global/Spinner.tsx, packages/frontend/src/components/notifications/Notifications.tsx, packages/frontend/src/components/notifications/RefreshNotifications.tsx, packages/frontend/src/components/notifications/SingleNotification.tsx, packages/frontend/src/hooks/useIsMounted.ts, packages/frontend/src/hooks/useNotifications.ts, packages/frontend/src/pages/_app.tsx, packages/frontend/src/pages/notifications.tsx, packages/frontend/src/styles/globals.css, packages/frontend/types/notifications/index.ts
- Adds a global `NotificationsContext` to maintain notifications state for menu component and page
----
- Blue dot to indicate an unread notification, option to mark individual notification as read
<div style="display: flex">
</div>
----
- Border outline on hover
----
- Show last refresh
----
- Error handling (added errors to the `NotificationsContext`, this isn't clean but it works for now)
=> Notifications UI updates

packages/frontend/src/components/userInput/NameSelect.tsx
Fixes the bug that closes the tab when you select an identity.
@grace-fagan 
Not sure why `close` was there, but lmk if there're contexts I'm missing.
=> Remove `close()` calls on name selection

packages/frontend/public/api-doc.yml, packages/frontend/src/components/Posts.tsx, packages/frontend/src/pages/api/v1/posts.ts, packages/frontend/src/pages/api/v1/utils.ts
Infinite scroll of posts for the home page.
- Switch useQuery to [useInfiniteQuery](https://tanstack.com/query/v4/docs/react/guides/infinite-queries).
- Switch to server-side sorting.
- Use the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to determine the timing to feth the next chunk. More precisely, when the last element of the currently fetched chunk comes into the viewport (i.e. user's view), we fetch the next chunk. We can make the timing to fetch the next chunk to be earlier if necessary. But when we make it too early the scrolling experience becomes a little weird (the scroll bar bounces back up mid-scroll).
Notes
- The all-users and (single) user pages don't do paginations; they fetch all data simultaneously. It might be …
=> Infinite scroll for home page

dev-accounts.json, packages/db/prisma/migrations/20230615135702_tree_many_to_many/migration.sql, packages/db/prisma/migrations/20230615140108_non_unique_tree_node/migration.sql, packages/db/prisma/schema.prisma, packages/frontend/src/pages/api/v1/groups/latest.ts, packages/merkle_tree/package.json, packages/merkle_tree/src/writeTree.ts, packages/merkle_tree/tsconfig.json, packages/test_data/scripts/populateTestData.ts, packages/test_data/tsconfig.json, render.yaml
- Store the entire history of the nouner Merkle tree in the database.
- We still only allow generating proofs with the latest set, but as we want to allow generating proofs with a static root after launch, making the necessary db changes before launch to make the transition easier.
- Make it easier to add dev accounts/beta testers. (just add them to [dev-accounts.json](https://github.com/personaelabs/nym/blob/dan/render-cleanup/dev-accounts.json))
- Remove Render preview environments as we're not using them.
Testing this in local is a little tedious (you'll need to set alchemy/etherscan API keys) so I think we can merge and see if it works (confirmed that it works in my env)  but lmk if you still wanna test before merging!
The main thing is that I wanna let you know I'm making the above …
=> Store the entire history of the Merkle trees in the database.

packages/frontend/public/api-doc.yml, packages/frontend/src/components/Posts.tsx, packages/frontend/src/pages/api/v1/posts.ts, packages/frontend/src/pages/api/v1/users/[userId]/posts.ts, packages/frontend/src/pages/api/v1/utils.ts, packages/frontend/types/api/index.ts, packages/frontend/types/api/queries.ts
After discussions with @cha0sg0d and joel from nerman, realized we need our public /posts/ API to serve posts+replies. This PR adds that and refactors the query logic in `selectAndCleanPosts` a bit
Closes #208 
The new API is as follows:
- Users can submit a timestamp for startTime AND OR endTime. If startTime exists, we get posts after or equal to that time. If endTime exists, we get posts before or equal to that time. If `rootOnly` is true, we only get root posts. By default, we get all post and replies.
Example:
HTTP GET `https://nouns.nymz.xyz/api/v1/posts?startTime=1687412894&endTime=1687474267293`
=> Allow replies in public posts API

packages/frontend/src/components/global/Seo.tsx, packages/frontend/src/lib/text.ts
Open to feedback here, but a nouner made the point that it's probably worthwhile to have common naming for this thing across platforms. 
I.e. the url is nouns.nymz, but the title of the site is 'Noun nyms'. Figure it makes sense to standardize on the URL but curious wyt @grace-fagan
=> Change title to Nouns Nymz everywhere
